### ISSUE TITLE
persistent memos

### ISSUE THREAD

**Issue by BLSTAFF** [erk91495/BL_Orders_2023#323] opened 2024-02-09 18:07 UTC
Submitter: Julie Burrowes
recurring memo for invoices such as Just Natural and Ideal Meat deliveries or "email invoice to customer" (ie Erie Bone Broth would like this)

**Comment by erk91495** [comment] 2024-03-08 14:51
Duplicate of #344

**Closed** 2024-03-08 14:51 UTC
Labels: duplicate, enhancement
