### ISSUE TITLE
Pallet Ticket(2nd request)

### ISSUE THREAD

**Issue by BLSTAFF** [erk91495/BL_Orders_2023#409] opened 2024-09-04 13:52 UTC
Submitter: TP
On Pallet Loading Report in Upper left-hand corner each ticket reads: "Pallet 1 of X." The first ticket should be "1 of X" the second should be "2 of X" etc.,etc. So on and so forth.

**Comment by erk91495** [comment] 2024-09-04 19:51
Duplicate of #408

**Closed by erk91495** 2024-09-04 19:51 UTC
Labels: bug
